### ISSUE TITLE
Suggestion: Rename the repository from MNIST to something else

### ISSUE THREAD

**Issue by rhiever** [zalandoresearch/fashion-mnist#1]
Someone [commented](https://www.reddit.com/r/MachineLearning/comments/6vzch9/p_fashionmnist_a_mnistlike_fashion_product/dm48ik9/) about this issue on Reddit (pasted below) and I think you should seriously consider changing the name of the benchmark to something else while it's still early on.

>MNIST stands for "Modified National Institute of Standards and Technology" and "National Institute of Standards and Technology" might not be too happy with their name being used. Call it something else. Especially when its an entirely new dataset and not a modification/extension of original NIST dataset.

**Comment by hanxiao** [comment]
thanks for reporting. Will do this asap

**Comment by lopuhin** [comment]
Even if it's legal, using the name MNIST for something that is not related to the NIST database seems confusing.

**Comment by robbiebarrat** [comment]
As long as the legal team is alright with it - I think that including MNIST in the title is actually pretty great and not confusing, because even though the dataset is totally different than MNIST, it is related since it's a _drop-in replacement_ for MNIST. It sets out to fix many issues in the original MNIST handwritten digits dataset; and serves the exact same purpose as the original.

**Comment by rhiever** [comment]
Good idea, @hanxiao. Otherwise, great job with this benchmark and thank you for sharing it! I'm already running [TPOT](https://github.com/rhiever/tpot) on your benchmark to see how it works.

@robbiebarrat, technically MNIST was called the ["MNIST database of handwritten digits"](http://yann.lecun.com/exdb/mnist/). The handwritten digits database is not called MNIST, though I think that fact was lost in time. A more appropriate shorthand name would be "digits" or something similar.

**Comment by Dexdev08** [comment]
or just call it fashion-digits...

**Comment by robbiebarrat** [comment]
@rhiever Oooh i didn't know that the handwritten dataset wasn't actually referred to as MNIST... Oops...

I think fashioNISTa would be a great name, though!

**Comment by hanxiao** [comment]
Some updates in this thread:

1. Zalando's legal team said they are fine with the name "Fashion-MNIST".
2. "MNIST" is not a registered trademark according to http://tmsearch.uspto.gov/bin/gate.exe?f=searchss&state=4810:neet52.1.1
3. We found datasets with "*NIST" in the name e.g. http://www.cs.toronto.edu/~tijmen/affNIST/, http://www.garrickorchard.com/datasets/n-mnist
4. Yann LeCun himself posted Fashion-MNIST on his Facebook page, so it seems that he is not angry with the name. https://www.facebook.com/yann.lecun/posts/10154714939492143

**Comment by rhiever** [comment]
To be clear: I raised this issue not because of legal concerns, but because (as discussed above) naming it with MNIST in the name doesn't actually make sense. MNIST refers to the institution that originally provided the digits dataset, not the dataset itself.

**Comment by andrewluetgers** [comment]
The original NIST digits database is now called "NIST Special Database 19" at the time Yann Lecun created MNIST it was SD 3 and 1. Someone could have made a modified version of the NIST fingerprint or mugshot datasets and named them MNIST prints and MNIST mugs, with just as much accuracy. But nobody did and so the shorthand is globally unique in the world that it is meaningful in (AI research dataset names) But not specific if you want to be pedantic about it you have to tack on the "handwritten digits" part. NIST acknowledges as much by having an official NIST version of MNIST called EMNIST https://www.nist.gov/itl/iad/image-group/emnist-dataset

In the horse and buggy days "dashboard" meant one thing and then something else in the age of the auto and yet something else in the information age so too MNIST in this case is (IMHO) an equally understandable moniker that does not mean what it technically is supposed to mean but captures a gestalt that everyone immediately grasps.

**Comment by rhiever** [comment]
OK. I still believe that it's a poor decision to continue misusing the MNIST name in this manner, but ultimately it's not my repo so I'll close the issue.
