### ISSUE TITLE
Benchmark: Wide ResNet and DenseNets

### ISSUE THREAD

**Issue by ajbrock** [zalandoresearch/fashion-mnist#10]
WRN40-4 lands at 3.93% error using standard preprocessing (mean/std subtraction/division) and augmentation (random crops/horizontal flips), Nesterov Momentum with a half-wave cosine annealing schedule and an initial LR of 0.1, trained for 300 epochs. DenseNet-BC with k=12 and D=100 land at 4.64% error with the same settings and 100 epochs of training, currently running a 300 epoch run. The WRN has 8.9M params, the DenseNet-BC has 768K params.

**Comment by happynear** [comment]
Hi @ajbrock,
Can you provide the network architecture here?

**Comment by hanxiao** [comment]
hi @ajbrock Many thanks for submitting the benchmark, I added to README. It would be nice if you can provide a source code reference.

**Comment by ajbrock** [comment]
Wide ResNet [here](https://github.com/xternalz/WideResNet-pytorch), DenseNets [here](https://github.com/bamos/densenet.pytorch), the code I used to train [here](https://github.com/ajbrock/FreezeOut), run without any FreezeOut.
