### ISSUE TITLE
The download link of t10k-images-idx3-ubyte.gz is wrong

### ISSUE THREAD

**Issue by leftthomas** [zalandoresearch/fashion-mnist#107]
I have downloaded the `t10k-images-idx3-ubyte.gz` from the `readme` provided [download link](fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-images-idx3-ubyte.gz), but I checked the md5sum value is `9fb629c4189551a2d022fa330f9573f3`, it not the same as `readme` given, I have deleted it and redownload again for five times, it is wrong.

**Comment by hanxiao** [comment]
I just checked. There is no problem with the MD5 sum value.

On my mac:
```bash
$ curl http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-images-idx3-ubyte.gz
$ md5 t10k-images-idx3-ubyte.gz
MD5 (t10k-images-idx3-ubyte.gz) = bef4ecab320f06d8554ea6380940ec79
```

**Comment by leftthomas** [comment]
@hanxiao , you could check it on Ubuntu16.04,  I have checked it on mac, it is right, but on Ubuntu it is wrong, I have asked this problem on PyTorch torchvision Github issues.
![screenshot from 2018-03-12 20-48-10](https://user-images.githubusercontent.com/9991443/37284539-d4e52d90-2636-11e8-943b-99aac03ab82e.png)

**Comment by leftthomas** [comment]
@hanxiao I also tested on my new MacBook Pro, you could found the download link is wrong, it redirects to MNIST!
<img width="1036" alt="qq20180313-110213 2x" src="https://user-images.githubusercontent.com/9991443/37320314-1c2f6afe-26ae-11e8-8e9e-e785727d0a1c.png">

**Comment by hanxiao** [comment]
I've tested on Linux machine (at Shenzhen China), it gives the correct result as follows:

```
hanhxiao:~# wget http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-images-idx3-ubyte.gz
--2018-03-13 11:21:08--  http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-images-idx3-ubyte.gz
Connecting to 10.223.133.20:52107... connected.
Proxy request sent, awaiting response... 200 OK
Length: 4422102 (4.2M) [binary/octet-stream]
Saving to: ‘t10k-images-idx3-ubyte.gz’

100%[===================================================================================================>] 4,422,102    605KB/s   in 19s

2018-03-13 11:21:29 (223 KB/s) - ‘t10k-images-idx3-ubyte.gz’ saved [4422102/4422102]

hanhxiao:~# md5sum t10k-images-idx3-ubyte.gz
bef4ecab320f06d8554ea6380940ec79  t10k-images-idx3-ubyte.gz
```

I saw a `302 redirect` response from your screenshot. This is really suspicious. We are hosting the data file as static file on Amazon S3 bucket, we are not setting any redirect there.

**Comment by hanxiao** [comment]
@leftthomas Can you do following in bash and check where `302` happens?
```bash
curl -v -L http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-images-idx3-ubyte.gz --output /dev/null
```

**Comment by hanxiao** [comment]
Or,
```
curl -v -L http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-images-idx3-ubyte.gz -IX GET
```
or,
```
wget http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-images-idx3-ubyte.gz -qSO /dev/null
```

For example, on my linux the second method gives:
```
hanhxiao:~# wget http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-images-idx3-ubyte.gz -qSO /dev/null
  HTTP/1.1 200 OK
  x-amz-id-2: DK6MTacPtZm8r6WJMeSzrmG9DFQRTjnLc7irkMSCHcIF8UkZE5H2K2LSLwgTJs31AaEP5bZSoTk=
  x-amz-request-id: 2C990AB5ADEAA5D1
  Date: Tue, 13 Mar 2018 03:41:48 GMT
  Last-Modified: Thu, 31 Aug 2017 12:17:53 GMT
  ETag: "bef4ecab320f06d8554ea6380940ec79"
  Content-Type: binary/octet-stream
  Content-Length: 4422102
  Server: AmazonS3
  X-Cache: MISS from TENCENT
  X-Cache-Lookup: MISS from TENCENT
  Via: 1.1 TENCENT (squid/3.3.8)
  Connection: keep-alive
```

**Comment by leftthomas** [comment]
I just tried that two command on my Mac, and here are the results
<img width="864" alt="qq20180313-122533 2x" src="https://user-images.githubusercontent.com/9991443/37322726-581bcad8-26ba-11e8-95c5-cec3380fb2d4.png">
<img width="864" alt="qq20180313-122656 2x" src="https://user-images.githubusercontent.com/9991443/37322730-60c983d2-26ba-11e8-9400-ce850cc927a8.png">

**Comment by leftthomas** [comment]
@hanxiao Further more, I found not only the `t10k-images-idx3-ubyte.gz` is wrong, but also the `train-images-idx3-ubyte.gz` is wrong by using the `curl` command to download the datas on my Mac:
<img width="759" alt="qq20180313-123626 2x" src="https://user-images.githubusercontent.com/9991443/37322914-6bf8f55c-26bb-11e8-97ef-3ca4d33e9b26.png">
And if I use `wget` to download the datas on my Mac, it just only `train-images-idx3-ubyte.gz` is wrong:
<img width="1207" alt="qq20180313-124409 2x" src="https://user-images.githubusercontent.com/9991443/37323102-707d496a-26bc-11e8-9d9d-271715f6043e.png">

**Comment by leftthomas** [comment]
@hanxiao Thanks for your help, I'll convey this problem to our informatization office.

**Comment by YaoQ** [comment]
> I have downloaded the `t10k-images-idx3-ubyte.gz` from the `readme` provided [download link](fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-images-idx3-ubyte.gz), but I checked the md5sum value is `9fb629c4189551a2d022fa330f9573f3`, it not the same as `readme` given, I have deleted it and redownload again for five times, it is wrong.

I get same issue for downloading t10k-images-idx3-ubyte.gz with CMCC ISP, the md5sum is 9fb629c4189551a2d022fa330f9573f3, it is changed to minist testset. But when I use another server with different ISP (China Telecom), download the t10k-images-idx3-ubyte.gz again, the file is OK, md5sum is bef4ecab320f06d8554ea6380940ec79.
