### ISSUE TITLE
DNN-for-fashion-mnist（acc 98.96%）

### ISSUE THREAD

**Issue by SrCMpink** [zalandoresearch/fashion-mnist#110]
See my github for more details
https://github.com/SrCMpink/DNN-for-fashion-mnist

**Comment by hanxiao** [comment]
```
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("/tmp/data1/", one_hot=True, source_url='http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/')
```
is the correct way to load fashion-mnist, as written in our README.md

**Comment by SrCMpink** [comment]
@hanxiao "/tmp/data/" is MNIST, "/tmp/data1/" is fashion MNIST

**Comment by hanxiao** [comment]
Could you do basic plotting as suggest here? just to make sure you are using the right data
https://github.com/mpekalski/zalando/blob/master/problem.ipynb

**Comment by SrCMpink** [comment]
@hanxiao I'm a little busy right now，but I can guarantee that this is indeed not MNIST. You can test it. Put your fashion-mnist into /tmp/data1/

**Comment by hanxiao** [comment]
don't be so sure about your result and please test your code again.

If you look at our [dashboard in README.md](https://github.com/zalandoresearch/fashion-mnist#benchmark). Simple CNN can't go beyond 93%. It has been tested by number of submissions from different researchers.

I know you are busy, and I can wait.

**Comment by hanxiao** [comment]
You can also check MD5 of the data with `md5` or `md5sum`. For example doing 
```bash
md5sum *.gz
```
should yield
```
bef4ecab320f06d8554ea6380940ec79  t10k-images-idx3-ubyte.gz
bb300cfdad3c16e7a12a480ee83cd310  t10k-labels-idx1-ubyte.gz
8d4fb7e6c68d591d4c3dfef9ec88bf0d  train-images-idx3-ubyte.gz
25c81989df183df01b3e8a0aad5dffbe  train-labels-idx1-ubyte.gz
```
which is consistent with the [MD5 in the README.md](https://github.com/zalandoresearch/fashion-mnist#get-the-data)

**Comment by SrCMpink** [comment]
Time will check everything.
I hope to have some one to test my code.
I think you are insulting my IQ. I can't even distinguish between MNIST and fashion MNIST?
Simple CNN can't go beyond 93%？I think there will be proof that you are wrong.
