### ISSUE TITLE
Validation Performance

### ISSUE THREAD

**Issue by heitorrapela** [zalandoresearch/fashion-mnist#113]
Hello there, this MLP results says in the author README that 90% is the Validation Performance, not the test.

MLP 256-128-64 | None | 0.900 | - | @lianghong |  
-- | -- | -- | -- | -- | --

**Comment by hanxiao** [comment]
thanks for pointing it out! will remove it from the table

**Comment by heitorrapela** [comment]
Nice, I opened an issue in his repository too, asking for test performance, because I'm training this dataset with MLP and I want to compare xD

**Comment by hanxiao** [comment]
cool, would be great if you can make a PR and add your MLP result here.

**Comment by heitorrapela** [comment]
Sure, let me organize a repo with only fashion-mnist, because that one that I`m working there are other features for other purposes :P
