### ISSUE TITLE
Code link is 404

### ISSUE THREAD

**Issue by dythebs** [zalandoresearch/fashion-mnist#123]
![image](https://user-images.githubusercontent.com/37578699/43188710-5ddc584e-9027-11e8-9e47-2c7b8098a0be.png)

**Comment by kashif** [comment]
thanks @dythebs the code was deleted... but we should link to the commit:

https://github.com/hardmaru/pytorch_notebooks/blob/be0f65f54ebca0da1e10ea5ecb2bd54ca4b794cb/pytorch_tiny_custom_mnist_adam.ipynb
