### ISSUE TITLE
Wrong url of test data

### ISSUE THREAD

**Issue by lijinfeng0713** [zalandoresearch/fashion-mnist#131]
Maybe you give a wrong url of test data in 'Get the Data' section

**Comment by hanxiao** [comment]
Not possible.
```
$ md5 *-ubyte.gz
MD5 (t10k-images-idx3-ubyte.gz) = bef4ecab320f06d8554ea6380940ec79
MD5 (t10k-labels-idx1-ubyte.gz) = bb300cfdad3c16e7a12a480ee83cd310
```

**Comment by lijinfeng0713** [comment]
The test data is 4.3 M, but the downloaded data is 1.6M, is the handwritten digit MNIST

**Comment by fdy200533** [comment]
> The test data is 4.3 M, but the downloaded data is 1.6M, is the handwritten digit MNIST

Same problem with u
