### ISSUE TITLE
Link to Pytorch Dataset broken

### ISSUE THREAD

**Issue by LakshyAAAgrawal** [zalandoresearch/fashion-mnist#171]
The following link in the README leads to a "Dead end" page: https://pytorch.org/docs/stable/torchvision/datasets.html#fashion-mnist

**Comment by kashif** [comment]
thanks for letting us know! I'll get it fixed ASAP

**Comment by LakshyAAAgrawal** [comment]
That was a very quick and helpful response. Thank you!
