### ISSUE TITLE
Is there a colored dataset?

### ISSUE THREAD

**Issue by Dexdev08** [zalandoresearch/fashion-mnist#2]
I'm not an expert -- but shouldn't a canonical fashion dataset, which seems to be the objective of this repo, be in color?

Not that I'm complaining much - this is a great contribution... but i think it will be of more contribution if it were in color and a bit bigger? and preprocess to become grayscale...

**Comment by kashif** [comment]
we wanted to keep the data size small as in the digits database. We might try to get a cifar-10 equivalent version... will keep you posted
