### ISSUE TITLE
Benchmark (MXNet gluon)

### ISSUE THREAD

**Issue by lianghong** [zalandoresearch/fashion-mnist#28]
Tried a simple 2-layer conv net with MXNet gluon  Accuracy is as follows:

[Epoch 24] Training: accuracy=0.935683
[Epoch 24] Validation: accuracy=0.900500

https://github.com/lianghong/fashion_mnist-on-mxnet

**Comment by hanxiao** [comment]
Thanks for your contribution, is this a conv net? Not very familiar with mxnet api, but I found only dense layers here.
https://github.com/lianghong/fashion_mnist-on-mxnet/blob/903b31b1dab8c02c80c534c7a21ccd9139228521/fashion-mnist.py#L38

btw, training accuracy shouldn't be the focus, as large network can achieve 100% training accuracy (but overfitting).
