### ISSUE TITLE
AlexNet with Triplet loss Benchmark

### ISSUE THREAD

**Issue by cenkbircanoglu** [zalandoresearch/fashion-mnist#34]
I use AlexNet for feature extraction with Triplet Loss function and embedding creation part, and I use Linear SVM for classifier.
I got accuracies as;
Train: 0.9946
Test: 0.8989

**Comment by philip-bl** [comment]
Do you know by any chance how many parameters your AlexNet had? Or is parameter count the same as in the original AlexNet paper?
