### ISSUE TITLE
3 Conv 2 FC layer Benchmark

### ISSUE THREAD

**Issue by cenkbircanoglu** [zalandoresearch/fashion-mnist#35]
I use 3 Conv and 2 FC layered network for feature extraction with Cosine Loss function and embedding creation part, and I use Linear SVM for classifier.
I got accuracies as;
Train: 0.9838
Test: 0.9072

**Comment by cenkbircanoglu** [comment]
I have 12 different results for this network without any preprocessing part. I just open 3 issues.

**Comment by hanxiao** [comment]
Thanks for your contribution, would be nice if you can provide a link to the source code.

**Comment by cenkbircanoglu** [comment]
https://github.com/cenkbircanoglu/openface/tree/master/fashion_mnist
This is code. But I havent prepare a script to download, preprocess and train the data. But I can do it in my free time
