### ISSUE TITLE
Is it possible to get the colored version?

### ISSUE THREAD

**Issue by pkern90** [zalandoresearch/fashion-mnist#38]
I wanted to ask if you could please also publish the colored version of the dataset. To be precise after the processing step 5 (extending) and before 6 (negating). This could, for example, be helpful for Image translation tasks.

**Comment by mpekalski** [comment]
On LinkedIn the authors replied that they have no plans to release colored version.

**Comment by hanxiao** [comment]
@pkern90 Please check response to #2
