### ISSUE TITLE
Convert dataset in t7 format for Torch research project usage

### ISSUE THREAD

**Issue by mingloo** [zalandoresearch/fashion-mnist#55]
Hi,

I've converted the original Fashion-MNIST dataset format from `Python/Numpy` format to `t7` [format](https://github.com/mingloo/train-a-fashion-classifier/blob/master/download/fashion-mnist.t7.tgz) for [Torch](https://github.com/torch/torch7) users.
The demo code for Fashion-MNIST classification can be seen from [train-a-fashion-classifier](https://github.com/mingloo/train-a-fashion-classifier).

It could be useful for Torch users.

**Comment by mingloo** [comment]
Motivated by Ronan Collobert's [mnist](https://github.com/andresy/mnist), I create a [fashion-mnist](https://github.com/mingloo/fashion-mnist), therefore the Torch user could simply use Fashion-MNIST dataset in their project by typing the following command:
```
luarocks install https://raw.github.com/mingloo/fashion-mnist/master/rocks/fashion-mnist-scm-1.rockspec
```
I think it could be the easy way for Torch users using Fashion-MNIST dataset.

**Comment by hanxiao** [comment]
@mingloo Greatly appreciated! I don't know very much about Torch community and how it works. Is it possible to push this helper to the torch master repo?
