### ISSUE TITLE
Link in arxiv has extra period at the end

### ISSUE THREAD

**Issue by csanhuezalobos** [zalandoresearch/fashion-mnist#62]
Hey guys,

Thank you for publishing this new dataset.
No an issue really wiht the dataset, but the link that you have in the arxiv's abstract has an extra period at the end.

Regards

**Comment by hanxiao** [comment]
Thanks for your report. Fortunately, the link is placed on the https://github.com/zalandoresearch/fashion-mnist without period. So clicking on it will lead you to the this github page. However, if you print the paper then the ending period is misleading.
