### ISSUE TITLE
docs: Additional measure for benchmarking

### ISSUE THREAD

**Issue by AFAgarap** [zalandoresearch/fashion-mnist#65]
Perhaps it would be good if we include not only the architecture used, preprocessing, training accuracy, and test accuracy in the benchmarks, but also include the time it took to train on `Fashion` v. `MNIST`. What do you think?

**Comment by hanxiao** [comment]
hmm, but the time measurement is always tricky and usually with high variance. It depends on package, language, cpu/gpu, etc.

**Comment by AFAgarap** [comment]
Well, yeah. Seems not a good idea for the open-source benchmarking.
