### ISSUE TITLE
Benchmark: Wide ResNet 28-10 + Random Erasing, Top-1 accuracy: 96.35%

### ISSUE THREAD

**Issue by zhunzhong07** [zalandoresearch/fashion-mnist#66]
Hi, we achieve 95.99% top-1 accuracy with using WRN-28-10 on Fashion-MNIST using standard preprocessing (mean/std subtraction/division) and augmentation (random crops/horizontal flips).

When using WRN-28-10 + [Random Erasing](https://arxiv.org/abs/1708.04896), it gives 96.35% top-1 accuracy.

The code will be available soon on [github](https://github.com/zhunzhong07/Random-Erasing).

**Comment by hanxiao** [comment]
cool, would be really nice to have fashion-mnist in your camera-ready!

**Comment by hanxiao** [comment]
fixed

**Comment by zhunzhong07** [comment]
@hanxiao We will report fashion-mnist results in the last version.

**Comment by AdityaGupta-IITD** [comment]
How much time did it take to run this code to get an accuracy of 95.99?
I wrote my own custom WideResnet-28-2 (running code on Colab) and it's getting an accuracy of 94.5% without any data augmentation (although I will try it once) in 50 epochs.
