### ISSUE TITLE
MNIST-Fashion-CNN

### ISSUE THREAD

**Issue by abelusha** [zalandoresearch/fashion-mnist#73]
https://github.com/abelusha/MNIST-Fashion-CNN/blob/master/MNIST_Fashon_CNN_using_Keras.ipynb

**Preprocessing** :  Normalization
**Result:**
![result](https://user-images.githubusercontent.com/12251952/30832535-a70d5844-a24b-11e7-9a28-834af5239451.PNG)

**Keras based Architecture:**
![model_summary](https://user-images.githubusercontent.com/12251952/30832557-c0848dba-a24b-11e7-8792-586bf63754b5.PNG)

**Comment by kashif** [comment]
@abelusha would you mind also running the same network on MNIST to get a comparison?

**Comment by abelusha** [comment]
sure

**Comment by abelusha** [comment]
@kashif here it is 
https://github.com/abelusha/MNIST-hand-written-digits/blob/master/MNIST_Hand_Written_Image_recognition.ipynb

**Comment by abelusha** [comment]
how can I add my benchmark to the table ?

**Comment by abelusha** [comment]
how can I add my benchmark to the table ?
