### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by abelusha** [zalandoresearch/fashion-mnist#74]
**Jupyter notebook:**
 https://github.com/abelusha/MNIST-Fashion-CNN/blob/master/Fashon_MNIST_CNN_using_Keras_10_Runs.ipynb

**I re-Run my CNN model 10 times for taking an average accuracy.**
**Here is the model Result:**
![avg_fashion_mnist](https://user-images.githubusercontent.com/12251952/31045056-f9643002-a5db-11e7-8909-aebf4df7648b.PNG)

**Model HyperParameter:**
![model_64_hp](https://user-images.githubusercontent.com/12251952/31045088-61ccad54-a5dc-11e7-8e7d-d44ce4d9656c.PNG)

**Model Architecture:**

![model_64](https://user-images.githubusercontent.com/12251952/31045073-2a17a526-a5dc-11e7-9bcf-7d8d84261a25.PNG)

**Comment by abelusha** [comment]
@hanxiao & @kashif can you look at this issue ?

**Comment by hanxiao** [comment]
@abelusha sorry for late reply and thanks for your contribution. It's done.

**Comment by abelusha** [comment]
@hanxiao  thanks!
