### ISSUE TITLE
Loaders which use crop cause issue since difference in MNIST fashion and MNIST data in terms of pixels always black

### ISSUE THREAD

**Issue by namangl** [zalandoresearch/fashion-mnist#76]
Hi,

There is a difference in terms of a pixel which is always black in training images across all 60000 samples.

The original MNIST data has 67 pixels of 28*28 pixels

 which are zero across all 60000 train images.

I wrote a MATLAB script to check the same; please use [code.zip](https://github.com/zalandoresearch/fashion-mnist/files/1384532/code.zip) and run it on both data sets separately.

This makes all the parsers/ loaders which remove padding not work optimally with MNIST Fashion data.
E.g. The loader for MNIST Images for MATLAB mentioned in README.md (under this) doesn't work for MNIST Fashion data
https://de.mathworks.com/matlabcentral/fileexchange/27675-read-digits-and-labels-from-mnist-database?focused=5154133&tab=function

**Please remove all Loaders from README.md which remove padding; since there exists atleast one image in MNIST Fashion training data where pixel is non-black.**

**Comment by hanxiao** [comment]
thanks for digging into the problem! I removed the link to bad helper
