### ISSUE TITLE
Capsule Network on fashion-mnist, test error 93.55%

### ISSUE THREAD

**Issue by XifengGuo** [zalandoresearch/fashion-mnist#80]
**Preprocessing**   
- Scale pixel values to [0,1]
- Data augmentation: shift at most 2 pixel and horizontal flip.

**Keras model structure**   
![model](https://user-images.githubusercontent.com/20176064/32478105-a2b4ad36-c3bd-11e7-94d0-2f54a05ffde6.png)
________________________________________________________________________________
Total params: 8,153,360
Trainable params: 8,141,840
Non-trainable params: 11,520
__________________________________________________________________________________________________

**Training time**   
200 minutes

**Accuracy**   
93.55%

**Source code**   
https://github.com/XifengGuo/CapsNet-Fashion-MNIST

**CapsNet paper**   
[Sara Sabour, Nicholas Frosst, Geoffrey E Hinton. Dynamic Routing Between Capsules. NIPS 2017](https://arxiv.org/abs/1710.09829)

**Comment by hanxiao** [comment]
thanks a lot! 🙇
