### ISSUE TITLE
benchmark: Try HOG + SVM 

### ISSUE THREAD

**Issue by subalde** [zalandoresearch/fashion-mnist#83]
Just out of curiosity, I tried an old-fashioned HOG+SVM approach, with almost no tuning of the HOG parameters. 

**Training time:** 
50 minutes

**Test accuracy**: 
0.926

You can find the code [here](https://github.com/subalde/fashion-mnist) (Requires OpenCV!)

**Comment by ondrejsotolar** [comment]
I doubt that the result is that good. [This paper](https://www.researchgate.net/publication/332035279_Fashion-MNIST_classification_based_on_HOG_feature_descriptor_using_SVM) got only 86% accuracy using the same thing. I was able to get the training error basically to nothing, but it doesn't generalize well. I got 88% with HOG (4,4) + MLP.
