### ISSUE TITLE
Clustering performance

### ISSUE THREAD

**Issue by XifengGuo** [zalandoresearch/fashion-mnist#96]
@hanxiao 
I wonder what's the clustering performance of the state-of-the-art clustering algorithms on fashion-mnist. 
I tested my algorithm and got an accuracy of 0.59 and NMI of 0.63.
Have you collected other clustering results?
Thanks.

**Comment by hanxiao** [comment]
hello Xifeng, thanks for testing. unfortunately, I don't have other cluster benchmark for comparison. I may add a table if people start to benchmark clustering algorithms on this dataset. As for now, I can add your repo to the readme.md if you want.

**Comment by kashif** [comment]
@XifengGuo indeed I think the best one I saw was https://github.com/lmcinnes/umap but again I do not have any numbers

**Comment by XifengGuo** [comment]
＠hanxiao
Thanks, I'll keep investigating the new results of clustering algorithms on Fashion-Mnist.
I believe it will benefit unsupervised learning community if results of state-of-the-art clustering algorithms are collected.
I'm looking forward to it.

For now, I only tested the most popular deep clustering algorithm [Unsupervised Deep Embedding for Clustering Analysis (DEC)](http://proceedings.mlr.press/v48/xieb16.pdf). 
If you think it is appropriate, you can add my result to the readme.md as a start. I'll appreciate it.

|  **clustering model**  |  **Preprocessing**   |**Fashion performance**|**MNIST performance**|  **Submitter**  |  **Code**   
   :--------|:---:|:----:|:-------:|:-----:|----:
   |[DEC](http://proceedings.mlr.press/v48/xieb16.pdf)   | Normalization (just scale pixel values to [0,1]) | ACC=0.618; NMI=0.651   | ACC=0.912; NMI=0.869      | [XifengGuo](https://github.com/XifengGuo)    | https://github.com/XifengGuo/DEC-keras

**Comment by XifengGuo** [comment]
@kashif Thanks for bring https://github.com/lmcinnes/umap to me, it looks really amazing.
